name = "iceboy"

[verilog]
sources = ["test/harness/verilog/SB_SPRAM256KA.v"]

[synthesis]
top = "icebreaker_top"
command = "synth_ice40"


[pnr]
architecture = "ice40"
pin_file = "icebreaker.pcf"
package = "sg48"
device = "iCE40UP5K"

[packing]
tool = "icepack"

[upload]
tool="iceprog"

[simulation]
testbench_dir = "test"
simulator = "icarus"
