from __future__ import annotations

import argparse
import re
import sys
import zlib
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from typing import NoReturn


ROOT = Path(__file__).resolve().parent.parent
TOOL_VERSION = "bake_rom_image.py v1"
DETERMINISTIC_GENERATED_AT = "1970-01-01T00:00:00Z"
FUNC_RE = re.compile(r"^pub fn (?P<name>[a-zA-Z_][a-zA-Z0-9_]*)\(\) -> \[uint<8>; (?P<size>\d+)\] \{$")
BYTE_RE = re.compile(r"0x([0-9a-f]{2})u8")


@dataclass(frozen=True)
class SymbolEntry:
    bank: int
    address: int
    name: str


@dataclass(frozen=True)
class BakedRom:
    rom_path: Path
    sym_path: Path | None
    identifier: str
    payload: bytes
    title: str
    cart_type: int
    rom_size_byte: int
    ram_size_byte: int
    crc32: int
    sha256_hex: str


def fail(message: str) -> NoReturn:
    raise SystemExit(message)


def root_relative(path: Path | None) -> str:
    if path is None:
        return "<none>"
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def sanitize_identifier(raw: str) -> str:
    identifier = re.sub(r"[^0-9a-zA-Z_]+", "_", raw.strip()).strip("_").lower()
    if not identifier:
        fail("failed to derive a valid identifier")
    if identifier[0].isdigit():
        identifier = f"rom_{identifier}"
    return identifier


def parse_title(rom_bytes: bytes) -> str:
    return rom_bytes[0x134:0x144].split(b"\x00", 1)[0].decode("ascii", "replace")


def parse_sym(path: Path) -> list[SymbolEntry]:
    entries: list[SymbolEntry] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith(";"):
            continue
        prefix, _, name = line.partition(" ")
        if not _:
            continue
        bank_text, _, addr_text = prefix.partition(":")
        if len(bank_text) != 2 or len(addr_text) != 4:
            continue
        try:
            bank = int(bank_text, 16)
            address = int(addr_text, 16)
        except ValueError:
            continue
        entries.append(SymbolEntry(bank=bank, address=address, name=name.strip()))
    return entries


def validate_sym_bounds(sym_entries: list[SymbolEntry], size: int) -> None:
    for entry in sym_entries:
        if entry.bank == 0 and entry.address < 0x8000 and entry.address >= size:
            fail(
                f"symbol '{entry.name}' at 00:{entry.address:04x} exceeds baked size {size}"
            )


def warn_if_non_ff_tail(rom_bytes: bytes, size: int) -> None:
    for offset, value in enumerate(rom_bytes[size:], start=size):
        if value != 0xFF:
            print(
                f"warning: ROM tail beyond size contains non-0xFF byte at 0x{offset:04x}: 0x{value:02x}",
                file=sys.stderr,
            )
            return


def build_baked_rom(
    *,
    rom_path: Path,
    sym_path: Path | None,
    size: int,
    identifier: str,
) -> BakedRom:
    if size <= 0:
        fail("--size must be positive")
    if not rom_path.is_file():
        fail(f"missing ROM file: {rom_path}")
    rom_bytes = rom_path.read_bytes()
    if size > len(rom_bytes):
        fail(f"--size {size} exceeds ROM length {len(rom_bytes)} for {rom_path}")
    if sym_path is not None:
        if not sym_path.is_file():
            fail(f"missing sym file: {sym_path}")
        validate_sym_bounds(parse_sym(sym_path), size)

    if size < len(rom_bytes):
        warn_if_non_ff_tail(rom_bytes, size)

    payload = rom_bytes[:size]
    return BakedRom(
        rom_path=rom_path,
        sym_path=sym_path,
        identifier=identifier,
        payload=payload,
        title=parse_title(rom_bytes),
        cart_type=rom_bytes[0x147],
        rom_size_byte=rom_bytes[0x148],
        ram_size_byte=rom_bytes[0x149],
        crc32=zlib.crc32(payload) & 0xFFFFFFFF,
        sha256_hex=sha256(payload).hexdigest(),
    )


def render_spade(baked: BakedRom) -> str:
    lines = [
        f"// Generated by {TOOL_VERSION}",
        f"// Generated UTC: {DETERMINISTIC_GENERATED_AT}",
        f"// Source ROM: {root_relative(baked.rom_path)}",
        f"// Source SYM: {root_relative(baked.sym_path)}",
        f"// ROM title: {baked.title}",
        f"// Cart type: 0x{baked.cart_type:02x}",
        f"// ROM size byte: 0x{baked.rom_size_byte:02x}",
        f"// RAM size byte: 0x{baked.ram_size_byte:02x}",
        f"// Truncated size: {len(baked.payload)}",
        f"// CRC32: 0x{baked.crc32:08x}",
        f"// SHA256: {baked.sha256_hex}",
        "",
        f"pub fn {baked.identifier}() -> [uint<8>; {len(baked.payload)}] {{",
        "    [",
    ]

    for start in range(0, len(baked.payload), 16):
        chunk = baked.payload[start : start + 16]
        rendered = ", ".join(f"0x{byte:02x}u8" for byte in chunk)
        suffix = "," if start + 16 < len(baked.payload) else ""
        lines.append(f"        {rendered}{suffix}")

    lines.extend(
        [
            "    ]",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def parse_generated_spade(path: Path) -> tuple[str, int, bytes]:
    identifier: str | None = None
    size: int | None = None
    payload = bytearray()

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        match = FUNC_RE.match(line)
        if match is not None:
            identifier = match.group("name")
            size = int(match.group("size"))
        for match in BYTE_RE.finditer(line):
            payload.append(int(match.group(1), 16))

    if identifier is None or size is None:
        fail(f"failed to parse generated Spade file: {path}")
    if len(payload) != size:
        fail(f"generated payload length mismatch in {path}: expected {size}, found {len(payload)}")
    return (identifier, size, bytes(payload))


def derive_identifier(args: argparse.Namespace) -> str:
    if args.name:
        return sanitize_identifier(args.name)
    if getattr(args, "out", None) is not None:
        return sanitize_identifier(Path(args.out).stem)
    if getattr(args, "validate", None) is not None:
        identifier, _, _ = parse_generated_spade(Path(args.validate))
        return identifier
    fail("failed to derive identifier")


def bake_command(args: argparse.Namespace) -> int:
    out_path = Path(args.out)
    identifier = derive_identifier(args)
    baked = build_baked_rom(
        rom_path=Path(args.rom),
        sym_path=Path(args.sym) if args.sym else None,
        size=args.size,
        identifier=identifier,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_spade(baked), encoding="utf-8")
    print(
        f"wrote {root_relative(out_path)} size={len(baked.payload)} crc32=0x{baked.crc32:08x} sha256={baked.sha256_hex}"
    )
    return 0


def validate_command(args: argparse.Namespace) -> int:
    generated_path = Path(args.validate)
    if not generated_path.is_file():
        fail(f"missing generated file: {generated_path}")

    identifier, size, payload = parse_generated_spade(generated_path)
    if args.size != size:
        fail(f"--size {args.size} does not match generated payload size {size} in {generated_path}")

    baked = build_baked_rom(
        rom_path=Path(args.rom),
        sym_path=Path(args.sym) if args.sym else None,
        size=args.size,
        identifier=identifier,
    )
    expected = render_spade(baked)
    actual = generated_path.read_text(encoding="utf-8")
    if actual != expected:
        fail(f"generated file contents do not match {root_relative(generated_path)}")
    if payload != baked.payload:
        fail(f"generated payload bytes do not match {root_relative(generated_path)}")

    print(
        f"validated {root_relative(generated_path)} crc32=0x{baked.crc32:08x} sha256={baked.sha256_hex}"
    )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Bake truncated first-light ROM images into committed Spade data files.")
    parser.add_argument("--rom", required=True, help="Path to the source .gb ROM")
    parser.add_argument("--size", required=True, type=int, help="Truncated ROM size in bytes")
    parser.add_argument("--sym", help="Optional .sym file for bank-00 bounds validation")
    parser.add_argument("--name", help="Optional output identifier override")
    parser.add_argument("--out", help="Output .spade path")
    parser.add_argument("--validate", help="Validate an existing generated .spade file")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    if bool(args.out) == bool(args.validate):
        parser.error("pass exactly one of --out or --validate")
    if args.out:
        return bake_command(args)
    return validate_command(args)


if __name__ == "__main__":
    raise SystemExit(main())
